- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/test.xml') }}"
    name: test
    url: http://localhost:8080
    user: admin
    password: "{{jenkins_password}}"
  loop:
    - frontend
    - cart
    - catalogue