- name: Create Config file - {{item.dir}}/{{item.name}}
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job-{{item.name}}.xml
  vars:
    unique_key: lookup('community.general.random_string', special=false, upper=false, length=12)

- name: Create Job - {{item.dir}}/{{item.name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job-{{item.name}}.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.39.158:8080
    user: admin
    password: "{{jenkins_password}}"